### ISSUE TITLE
kubernetes-restart command not found

### ISSUE THREAD

**Issue by dalehamel** [Shopify/kubernetes-deploy#157] opened 2017-08-08 20:54 UTC
Ran into this trying to restart via shipit

```
Kube-restart failed
$ bundle exec kubernetes-restart identity-production tier3
pid: 20076
bundler: failed to load command: kubernetes-restart (/app/data/bundler/ruby/2.3.0/bin/kubernetes-restart)
```

@KnVerey @kirs right now folks trying to do a restart via shipit are hitting this bug

**Comment by dalehamel** [comment] 2017-08-08 20:56
from the gemspec it looks like this should work...

**Comment by kirs** [comment] 2017-08-08 20:59
The issue is that `kubernetes-restart` shouldn't be prepended by `bundle exec`.
It's being fixed by https://github.com/Shopify/shipit-engine/pull/715

cc @DazWorrall

**Comment by dalehamel** [comment] 2017-08-08 21:03
@kirs that's been merged, so do we just need to get that out?

**Comment by DazWorrall** [comment] 2017-08-08 21:10
The fix is deployed, it needs some cache busting, or is cleared on stack deploy. There's another issue still though, once the cache is updated: https://shipit.shopify.io/shopify/spy/staging/tasks/469174

Planned to raise it properly tomorrow, I'm on phone right now.

**Comment by dalehamel** [comment] 2017-08-08 21:13
cheers folks

**Comment by dalehamel** [comment] 2017-08-10 15:52
@DazWorrall did the fix go out here?

**Comment by DazWorrall** [comment] 2017-08-10 16:00
The first issue is resolved - i.e. we're not prepending `bundle exec` - but we're still failing with a cert error: https://shipit.shopify.io/shopify/spy/staging/tasks/470049

```
$ kubernetes-restart spy-staging tier4
pid: 18922
/usr/lib/ruby-shopify/ruby-shopify-2.3.3/lib/ruby/gems/2.3.0/gems/kubeclient-2.4.0/lib/kubeclient/common.rb:117:in `rescue in handle_exception': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (KubeException)
	from /usr/lib/ruby-shopify/ruby-shopify-2.3.3/lib/ruby/gems/2.3.0/gems/kubeclient-2.4.0/lib/kubeclient/common.rb:109:in `handle_exception'
	from /usr/lib/ruby-shopify/ruby-shopify-2.3.3/lib/ruby/gems/2.3.0/gems/kubeclient-2.4.0/lib/kubeclient/common.rb:461:in `fetch_entities'
	from /usr/lib/ruby-shopify/ruby-shopify-2.3.3/lib/ruby/gems/2.3.0/gems/kubeclient-2.4.0/lib/kubeclient/common.rb:451:in `load_entities'
	from /usr/lib/ruby-shopify/ruby-shopify-2.3.3/lib/ruby/gems/2.3.0/gems/kubeclient-2.4.0/lib/kubeclient/common.rb:121:in `discover'
	from /usr/lib/ruby-shopify/ruby-shopify-2.3.3/lib/ruby/gems/2.3.0/gems/kubernetes-deploy-0.12.0/lib/kubernetes-deploy/kubeclient_builder.rb:52:in `_build_kubeclient'
	from /usr/lib/ruby-shopify/ruby-shopify-2.3.3/lib/ruby/gems/2.3.0/gems/kubernetes-deploy-0.12.0/lib/kubernetes-deploy/kubeclient_builder.rb:17:in `build_v1_kubeclient'
	from /usr/lib/ruby-shopify/ruby-shopify-2.3.3/lib/ruby/gems/2.3.0/gems/kubernetes-deploy-0.12.0/lib/kubernetes-deploy/restart_task.rb:30:in `initialize'
	from /usr/lib/ruby-shopify/ruby-shopify-2.3.3/lib/ruby/gems/2.3.0/gems/kubernetes-deploy-0.12.0/exe/kubernetes-restart:19:in `new'
	from /usr/lib/ruby-shopify/ruby-shopify-2.3.3/lib/ruby/gems/2.3.0/gems/kubernetes-deploy-0.12.0/exe/kubernetes-restart:19:in `<top (required)>'
	from /usr/lib/ruby-shopify/ruby-shopify-2.3.3/bin/kubernetes-restart:22:in `load'
	from /usr/lib/ruby-shopify/ruby-shopify-2.3.3/bin/kubernetes-restart:22:in `<main>'
```

I wasn't able to reproduce this locally, and haven't had any time to dig deeper unfortunately.

**Comment by kirs** [comment] 2017-08-10 16:13
I've been looking into shipit [kubeconfig](https://github.com/Shopify/shipit/blob/master/config/kubeconfig.yml.erb) but I haven't found anything specific.

@dalehamel might be related to security changes that have been going on during M2?

**Comment by KnVerey** [comment] 2017-08-10 16:46
We saw that exact error when I tried to use kubeclient in ejson secret provisioner: [PR removing it](https://github.com/Shopify/kubernetes-deploy/pull/91), [deploy with error](https://shipit.shopify.io/shopify/hackdays-gke-rails5/production/deploys/445001). @xldenis that PR mentions that you were looking into it at the time. Did you figure anything out? @kirs did the restart task ever work in Shipit?

**Comment by kirs** [comment] 2017-08-14 07:55
iirc it worked for undercloud, which was using basic auth instead of SSL certificates.

**Comment by xldenis** [comment] 2017-08-15 14:30
Yea I remmber solving the issue I had with google authentication, I have totally forgotten everything about it but I think that's what the `GoogleFriendlyConfig` class is for...

**Comment by KnVerey** [comment] 2017-08-28 17:44
@DazWorrall @kirs any progress on this? @dturn is looking to hook this up to the restart command for core.

**Comment by DazWorrall** [comment] 2017-09-04 13:59
Took some digging but I think I've figured this out - we're bundling rest-client 1.6.9 on shipit (dependency of kubeclient) but the option to pass in your own certificate store was only added in [1.7.0](https://github.com/rest-client/rest-client/commit/f378ad154a6cc3a15c162552f6b1b08822885099). This should probably be fixed as a dependency upstream, as it's currently [unspecified](https://github.com/abonas/kubeclient/blob/30b8285411ecfb485f7cfd816684936e32d46ba6/kubeclient.gemspec#L30), we could also add our own version specifier in the mean time.

**Comment by DazWorrall** [comment] 2017-09-04 14:36
Bumped shipit to rest-client 1.7.0 and restarts are now succeeding - I'll leave the issue open in case you want to update the gem deps @KnVerey, or wait for upstream.

**Closed** 2017-11-08 17:55 UTC
